Repository Autodesk/hubble, pull requests merged in 2018-04, with the labels that each got.

#150 Make table chart type explicit
  docs/assets/js/charts.js
  docs/housekeeping-abandoned-orgs.html
  docs/housekeeping-api-requests.html
  docs/housekeeping-forks.html
  docs/housekeeping-git-requests.html
  docs/housekeeping-git-traffic.html
  docs/housekeeping-repo-location.html
  docs/org-owners.html
  docs/recommendations-legacy-teams.html
  docs/recommendations-tokenless-auth.html
  docs/repos-activity.html
Labels: enhancement, infrastructure

#144 Add detailed Git versions report
  updater/reports/ReportGitVersionsNew.py
  updater/update-stats.py
Labels: enhancement

#153 Support empty data repositories
  updater/schema.py
Labels: bug

#152 Add missing Python import directive
  updater/reports/ReportPRUsage.py
Labels: bug

#155 Improve some descriptions
  docs/housekeeping-git-traffic.html
  docs/repos-activity.html
  updater/reports/ReportRepoActivity.py
Labels: documentation
